services:

  nodejs-app:
    build: .
    container_name: nodejs-isolation-app
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - frontend
      - backend

  redis:
    image: redis:8-alpine
    container_name: redis-private
    networks:
      - backend

  debug-container:
    image: alpine:latest
    container_name: debug-network
    command: sh -c "apk add curl bind-tools && tail -f /dev/null"
    networks:
      - frontend

networks:
  frontend:
  backend:
    internal: true